version: '3.7'

services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    ports:
      - "27017:27017"
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"